# This config file is loaded by the node-config package (see dependencies in package.json)
#   if the NODE_ENV environment variable is set to 'dev' from the config var in the Heroku image.
#   Therefore, there is no need of the src/environments folder as the environment is set prior to app build

env: dev

backend:
  url: https://bonspiel-server-devl.herokuapp.com/

db:
  user: capstone
  pass: jWy8XTG36FcTtRUQPa2PqFvfjLqfsL
  host: bonspiel-1.cjb7ejiq8hxn.us-west-2.rds.amazonaws.com  
  port: 5432