openapi: 3.0.0
info:
  title: Bonspiel Tracking System API
  version: 0.1.0
servers:
  - url: 'localhost:8080/api/v1'
    description: Base url
  - url: 'localhost:8080/api/v1/admin'
    description: Admin url
paths:
  /events:
    get:
      summary: Returns all curling events
      responses:
        '200':
          description: A JSON array of curling event objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurlingEvent'
  '/events/{curling_event_id}/teams':
    get:
      summary: Returns all teams by curling_event_id
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: A JSON array of team objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  '/events/{curling_event_id}/games':
    get:
      summary: Returns all games by curling_event_id
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: A JSON array of game objects sorted by team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamGame'
  '/events/{curling_event_id}/draws':
    get:
      summary: Returns all draws by in a curling event
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: A JSON array of draw objects sorted by team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Draw'
  '/events/{curling_event_id}/teams/{team_id}/games':
    get:
      summary: Returns all games played by a team in a specific curling event
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
        - in: path
          name: team_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The team id
      responses:
        '200':
          description: A JSON array of game objects sorted by draw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DrawGame'
  '/events/{curling_event_id}/teams/{team_id}/scores':
    get:
      summary: >-
        Returns all scores and games played by a team in a specific curling
        event
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
        - in: path
          name: team_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The team id
      responses:
        '200':
          description: A JSON array of game objects sorted by draw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DrawGame'
  '/events/{curling_event_id}/scores':
    get:
      summary: Returns all games and scores in a specific curling event
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: A JSON array of game objects sorted by draw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
  '/events/{curling_event_id}/event-teams':
    get:
      summary: Returns a list of teams in an event
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: An array of teams
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: '#/components/schemas/Team'
  '/events/{curling_event_id}/generate-brackets':
    get:
      summary: Returns nodes and edges for bracket generation
      parameters:
        - in: path
          name: curling_event_id
          required: true
          schema:
            type: integer
            minimum: 0
          description: The curling event id
      responses:
        '200':
          description: A JSON with nodes and edges
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: string
                edges:
                  type: array
                  items:
                    type: string
  /teams:
    get:
      summary: Returns all teams
      responses:
        '200':
          description: all teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  'teams/{team_id}':
    get:
      summary: Returns a single team
      responses:
        '200':
          description: the requested team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
  /orgs:
    get:
      summary: Returns all orgs
      responses:
        '200':
          description: the requested orgs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
  '/orgs/{orgId}':
    get:
      summary: Returns requested organization
      parameters:
        - in: path
          name: orgId
          required: true
          schema:
            type: integer
            minimum: 0
          description: The org id
      responses:
        '200':
          description: the requested org
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
  '/orgs/{orgId}/curlers':
    get:
      summary: Returns all curlers in org
      parameters:
        - in: path
          name: orgId
          required: true
          schema:
            type: integer
            minimum: 0
          description: The org id
      responses:
        '200':
          description: >-
            the requested curlers with `curlingteamname` attached to each curler
            object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curler'
  /query:
    post:
      summary: 'Queries the database without UPDATE, INSERT, CREATE, or DELETE'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Straight from the database
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    CurlingEvent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        begin_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        completed:
          type: boolean
        info:
          type: string
        event_type:
          type: string
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        event_type:
          type: string
        bracket_id:
          type: integer
          format: int64
        pool_id:
          type: integer
          format: int64
        curlingteam1_id:
          type: integer
          format: int64
        curlingteam2_id:
          type: integer
          format: int64
        ice_sheet:
          type: integer
        finished:
          type: boolean
        winner:
          type: integer
    TeamGame:
      type: object
      properties:
        team_name:
          type: string
    DrawGame:
      type: object
      properties:
        draw_id:
          type: integer
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
    Draw:
      type: object
      properties:
        draw_id:
          type: integer
        event_id:
          type: integer
        name:
          type: string
        start:
          type: date-time
        video-url:
          type: string
    Organization:
      type: object
      properties:
        id:
          type: integer
        short_name:
          type: string
        full_name:
          type: string
    Curler:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        position:
          type: string
        affiliation:
          type: integer
        curlingteam_id:
          type: integer
