


INSERT INTO CurlingEvent VALUES (DEFAULT, 'Granite Jr. Bonspiel', '1/25/2020', '1/26/2020', TRUE, 'Come on out to the State Fair.', 'pools');



INSERT INTO Organization VALUES (DEFAULT, 'ECC', 'Evergreen Curling Club');
INSERT INTO Organization VALUES (DEFAULT, 'GCC', 'Granite Curling Club');
INSERT INTO Organization VALUES (DEFAULT, 'DCC', 'Denver Curling Club');



INSERT INTO Pool VALUES (DEFAULT,  1, 'Animals', 'pink');
INSERT INTO Pool VALUES (DEFAULT,  1, 'Cattle-A', 'pink');
INSERT INTO Pool VALUES (DEFAULT,  1, 'Cattle-B', 'pink');



INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Piglettes', 'Winner');
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Pygmy Goats', '2nd place');
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Sheep', '3rd place');	
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Chickens', '4th place');
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Horses', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Rabbits', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Ayrshire', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Highland', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Holstein', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Jersey', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Brown Swiss', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Red Angus', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Hereford', NULL);
INSERT INTO CurlingTeam VALUES (DEFAULT, NULL, 'Guernsey', NULL);



INSERT INTO eventteams VALUES(1, 1);
INSERT INTO eventteams VALUES(1, 2);
INSERT INTO eventteams VALUES(1, 3);
INSERT INTO eventteams VALUES(1, 4);
INSERT INTO eventteams VALUES(1, 5);
INSERT INTO eventteams VALUES(1, 6);
INSERT INTO eventteams VALUES(1, 7);
INSERT INTO eventteams VALUES(1, 8);
INSERT INTO eventteams VALUES(1, 9);
INSERT INTO eventteams VALUES(1, 10);
INSERT INTO eventteams VALUES(1, 11);
INSERT INTO eventteams VALUES(1, 12);
INSERT INTO eventteams VALUES(1, 13);
INSERT INTO eventteams VALUES(1, 14);



INSERT INTO Curler VALUES (DEFAULT, 'Connor Kauffman', 'skip', 2, 1);
INSERT INTO Curler VALUES (DEFAULT, 'Alex Couckuyt', 'vice', 2, 1);
INSERT INTO Curler VALUES (DEFAULT, 'Andrew Bell', 'lead', 2, 1);
INSERT INTO Curler VALUES (DEFAULT, 'Arianna Rauliuk', 'skip', 2, 2);
INSERT INTO Curler VALUES (DEFAULT, 'Allison Tan', 'vice', 2, 2);
INSERT INTO Curler VALUES (DEFAULT, 'Abby Lin', 'second', 2, 2);
INSERT INTO Curler VALUES (DEFAULT, 'Mari Torii-Karch', 'lead', 2, 2);
INSERT INTO Curler VALUES (DEFAULT, 'Bowen Zheng', 'skip', 2, 3);
INSERT INTO Curler VALUES (DEFAULT, 'Alex Lee', 'vice', 2, 3);
INSERT INTO Curler VALUES (DEFAULT, 'Lennox Weiner', 'second', 2, 3);
INSERT INTO Curler VALUES (DEFAULT, 'Alex Ge', 'lead', 2, 3);
INSERT INTO Curler VALUES (DEFAULT, 'Meghan Taylor', 'skip', 1, 4);
INSERT INTO Curler VALUES (DEFAULT, 'Lehua Morley', 'vice', 1, 4);
INSERT INTO Curler VALUES (DEFAULT, 'Shiyon Kim', 'second', 1, 4);
INSERT INTO Curler VALUES (DEFAULT, 'Jacob Feldman', 'lead', 1, 4);
INSERT INTO Curler VALUES (DEFAULT, 'Steven Hagen', NULL, 1, 5);
INSERT INTO Curler VALUES (DEFAULT, 'Zander Emerson', NULL, 1, 5);
INSERT INTO Curler VALUES (DEFAULT, 'Alex Ellis', NULL, 1, 5);
INSERT INTO Curler VALUES (DEFAULT, 'Oliver Chally', NULL, 1, 5);
INSERT INTO Curler VALUES (DEFAULT, 'Rylie Watson', NULL, 2, 6);
INSERT INTO Curler VALUES (DEFAULT, 'Faye Alesse', NULL, 2, 6);
INSERT INTO Curler VALUES (DEFAULT, 'Locke Curfman', NULL, 2, 6);
INSERT INTO Curler VALUES (DEFAULT, 'Mara Durland', NULL, 2, 6);
INSERT INTO Curler VALUES (DEFAULT, 'Caiden Rose', NULL, 3, 7);
INSERT INTO Curler VALUES (DEFAULT, 'Avery Wilson,', NULL, 3, 7);
INSERT INTO Curler VALUES (DEFAULT, 'Genessa Capra', NULL, 3, 7);
INSERT INTO Curler VALUES (DEFAULT, 'Tate Reeder-Holman', NULL, 3, 7);
INSERT INTO Curler VALUES (DEFAULT, 'Max Carson', NULL, 3, 8);
INSERT INTO Curler VALUES (DEFAULT, 'William Curtiss,', NULL, 3, 8);
INSERT INTO Curler VALUES (DEFAULT, 'Max Hamlot', NULL, 3, 8);
INSERT INTO Curler VALUES (DEFAULT, 'Braydon Hanson', NULL, 3, 8);
INSERT INTO Curler VALUES (DEFAULT, 'Parker Casteel', NULL, 1, 9);
INSERT INTO Curler VALUES (DEFAULT, 'Preston Casteel', NULL, 1, 9);
INSERT INTO Curler VALUES (DEFAULT, 'Tess Ellis', NULL, 1, 9);
INSERT INTO Curler VALUES (DEFAULT, 'Zach Thompson', NULL, 1, 9);
INSERT INTO Curler VALUES (DEFAULT, 'Cyrus Stenzel', NULL, 1, 10);
INSERT INTO Curler VALUES (DEFAULT, 'Finley Snow', NULL, 1, 10);
INSERT INTO Curler VALUES (DEFAULT, 'Hamin Park', NULL, 1, 10);
INSERT INTO Curler VALUES (DEFAULT, 'Lexi Wong', NULL, 1, 10);
INSERT INTO Curler VALUES (DEFAULT, 'Tommy Miller', NULL, 3, 11);
INSERT INTO Curler VALUES (DEFAULT, 'Jack Hill', NULL, 3, 11);
INSERT INTO Curler VALUES (DEFAULT, 'Niko Hill', NULL, 3, 11);
INSERT INTO Curler VALUES (DEFAULT, 'Lila Farwell', NULL, 3, 11);



INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #1', '2020-01-25 08:30', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #2', '2020-01-25 10:15', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Lunch', '2020-01-25 12:15', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #3', '2020-01-25 13:15', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #4', '2020-01-25 15:30', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Banquet', '2020-01-25 17:30', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #5', '2020-01-25 19:00', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #6', '2020-01-26 09:00', NULL);
INSERT INTO Draw VALUES (DEFAULT, 1, 'Draw #7', '2020-01-26 11:30', NULL);



INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 2, 1, 7, 8, DEFAULT, DEFAULT, NULL, NULL,  '2', TRUE, 7); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 3, 1, 11, 12, DEFAULT, DEFAULT, NULL, NULL, '3', TRUE, 11); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 2, 1, 9, 10, DEFAULT, DEFAULT, NULL, NULL, '4', TRUE, 9); 

INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 2, 1, 3, DEFAULT, DEFAULT, NULL, NULL, '2', TRUE,  1); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 2, 2, 6, DEFAULT, DEFAULT, NULL, NULL, '3', TRUE,  2); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 2, 4, 5, DEFAULT, DEFAULT, NULL, NULL,  '5', TRUE,  4);

INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 3, 4, 13, 11, DEFAULT, DEFAULT, NULL, NULL,  '1', TRUE,  11); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 2, 4, 10, 7, DEFAULT, DEFAULT, NULL, NULL, '2', TRUE,  7); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 3, 4, 12, 14, DEFAULT, DEFAULT, NULL, NULL,  '3', TRUE, 12); 
 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 2, 5, 7, 9, DEFAULT, DEFAULT, NULL, NULL,  '1', TRUE,  7); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 3, 5, 11, 14, DEFAULT, DEFAULT, NULL, NULL,  '2', TRUE,  11); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 5, 5, 1, DEFAULT, DEFAULT, NULL, NULL,  '3', TRUE,  1);  

INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 7, 2, 5, DEFAULT, DEFAULT, NULL, NULL,  '1', TRUE, 2); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 7, 3, 6, DEFAULT, DEFAULT, NULL, NULL, '2', TRUE, 3);  
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 2, 7, 10, 8, DEFAULT, DEFAULT, NULL, NULL,  '3', TRUE, 8); 
 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 8, 1, 6, DEFAULT, DEFAULT, NULL, NULL,  '1', TRUE,  1); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 8, 4, 2, DEFAULT, DEFAULT, NULL, NULL,  '2', TRUE,  4); 
INSERT INTO Game VALUES (DEFAULT, 'pools', 'Pool Champs', NULL, NULL, 8, 11, 7, DEFAULT, DEFAULT, NULL, NULL, '3', TRUE, 7); 

INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 9, 5, 6, DEFAULT, DEFAULT, NULL, NULL,  '2', TRUE,  5); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 9, 3, 4, DEFAULT, DEFAULT, NULL, NULL,  '3', TRUE,  3); 
INSERT INTO Game VALUES (DEFAULT, 'pools', NULL, NULL, 1, 9, 2, 1, DEFAULT, DEFAULT, NULL, NULL, '4', TRUE,  1); 



INSERT INTO endscore VALUES (DEFAULT, 1, 1, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 1, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 1, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 1, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 1, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 1, 6, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 1, 7, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 1, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 2, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 2, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 2, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 2, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 2, 5, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 2, 6, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 2, 7, FALSE, TRUE, 3);
INSERT INTO endscore VALUES (DEFAULT, 2, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 3, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 3, 2, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 3, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 3, 4, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 3, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 3, 6, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 3, 7, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 3, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 4, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 4, 2, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 4, 3, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 4, 4, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 4, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 4, 6, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 4, 7, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 4, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 5, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 2, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 4, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 6, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 7, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 5, 8, FALSE, TRUE, 2);

INSERT INTO endscore VALUES (DEFAULT, 6, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 6, 2, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 6, 3, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 6, 4, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 6, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 6, 6, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 6, 7, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 6, 8, FALSE, TRUE, 3);

INSERT INTO endscore VALUES (DEFAULT, 7, 1, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 7, 2, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 7, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 7, 4, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 7, 5, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 7, 6, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 7, 7, FALSE, FALSE, 2);
INSERT INTO endscore VALUES (DEFAULT, 7, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 8, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 8, 2, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 8, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 8, 4, FALSE, FALSE, 2);
INSERT INTO endscore VALUES (DEFAULT, 8, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 8, 6, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 8, 7, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 8, 8, FALSE, FALSE, 2);

INSERT INTO endscore VALUES (DEFAULT, 9, 1, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 9, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 9, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 9, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 9, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 9, 6, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 9, 7, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 9, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 10, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 10, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 10, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 10, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 10, 5, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 10, 6, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 10, 7, FALSE, TRUE, 3);
INSERT INTO endscore VALUES (DEFAULT, 10, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 11, 1, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 11, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 11, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 11, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 11, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 11, 6, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 11, 7, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 11, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 12, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 12, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 12, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 12, 4, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 12, 5, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 12, 6, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 12, 7, FALSE, TRUE, 3);
INSERT INTO endscore VALUES (DEFAULT, 12, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 13, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 13, 2, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 13, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 13, 4, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 13, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 13, 6, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 13, 7, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 13, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 14, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 14, 2, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 14, 3, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 14, 4, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 14, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 14, 6, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 14, 7, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 14, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 15, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 2, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 4, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 6, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 15, 7, FALSE, FALSE, 2);
INSERT INTO endscore VALUES (DEFAULT, 15, 8, FALSE, TRUE, 0);

INSERT INTO endscore VALUES (DEFAULT, 16, 1, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 16, 2, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 16, 3, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 16, 4, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 16, 5, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 16, 6, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 16, 7, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 16, 8, FALSE, TRUE, 3);

INSERT INTO endscore VALUES (DEFAULT, 17, 1, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 17, 2, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 17, 3, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 17, 4, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 17, 5, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 17, 6, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 17, 7, FALSE, FALSE, 2);
INSERT INTO endscore VALUES (DEFAULT, 17, 8, FALSE, TRUE, 1);

INSERT INTO endscore VALUES (DEFAULT, 18, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 18, 2, FALSE, FALSE, 3);
INSERT INTO endscore VALUES (DEFAULT, 18, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 18, 4, FALSE, FALSE, 2);
INSERT INTO endscore VALUES (DEFAULT, 18, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 18, 6, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 18, 7, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 18, 8, FALSE, FALSE, 2);

INSERT INTO endscore VALUES (DEFAULT, 19, 1, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 19, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 19, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 19, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 19, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 19, 6, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 19, 7, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 19, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 20, 1, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 20, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 20, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 20, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 20, 5, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 20, 6, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 20, 7, FALSE, TRUE, 3);
INSERT INTO endscore VALUES (DEFAULT, 20, 8, FALSE, FALSE, 0);

INSERT INTO endscore VALUES (DEFAULT, 21, 1, FALSE, TRUE, 2);
INSERT INTO endscore VALUES (DEFAULT, 21, 2, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 21, 3, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 21, 4, FALSE, FALSE, 0);
INSERT INTO endscore VALUES (DEFAULT, 21, 5, FALSE, TRUE, 1);
INSERT INTO endscore VALUES (DEFAULT, 21, 6, FALSE, FALSE, 1);
INSERT INTO endscore VALUES (DEFAULT, 21, 7, FALSE, TRUE, 0);
INSERT INTO endscore VALUES (DEFAULT, 21, 8, FALSE, FALSE, 3);


INSERT INTO CurlingEvent VALUES(5, 'Hollywood Open', '7/4/2020', '7/5/2020', TRUE, NULL, 'pools');

INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Olsen Twins & Co', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'A Series of Unfortunate Ends', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, '#curlsquad', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Team Zissou', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Ill Fill This In Later', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, '2 Girls and Some Wildmen', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Hack to the Future', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'SL,UTs', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'The Slide Rulers', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Thats What She Said', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Hold Em to 1', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Danknasty Curling Presented by CurlingZone', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Sea Org Rejects', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Junk Up the Front', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Flock Yeah', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Grosse Pointe Blank Ends', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Casablankends', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Mystery Inc.', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'The Jerks', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Team Umali', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Double - Double Ds', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Curlers of the Lost Arc', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Bulls Team Awesome', '');
INSERT INTO CurlingTeam VALUES (DEFAULT, 1, 'Angry Canadiens', '');

INSERT INTO eventteams VALUES(5, 15);
INSERT INTO eventteams VALUES(5, 16);
INSERT INTO eventteams VALUES(5, 17);
INSERT INTO eventteams VALUES(5, 18);
INSERT INTO eventteams VALUES(5, 19);
INSERT INTO eventteams VALUES(5, 20);
INSERT INTO eventteams VALUES(5, 21);
INSERT INTO eventteams VALUES(5, 22);
INSERT INTO eventteams VALUES(5, 23);
INSERT INTO eventteams VALUES(5, 24);
INSERT INTO eventteams VALUES(5, 25);
INSERT INTO eventteams VALUES(5, 26);
INSERT INTO eventteams VALUES(5, 27);
INSERT INTO eventteams VALUES(5, 28);
INSERT INTO eventteams VALUES(5, 29);
INSERT INTO eventteams VALUES(5, 30);
INSERT INTO eventteams VALUES(5, 31);
INSERT INTO eventteams VALUES(5, 32);
INSERT INTO eventteams VALUES(5, 33);
INSERT INTO eventteams VALUES(5, 34);
INSERT INTO eventteams VALUES(5, 35);
INSERT INTO eventteams VALUES(5, 36);
INSERT INTO eventteams VALUES(5, 37);
INSERT INTO eventteams VALUES(5, 38);


INSERT INTO Draw VALUES (81, 5, 'Draw #1', '2020-07-04 11:40', '');
INSERT INTO Draw VALUES (82, 5, 'Draw #2', '2020-07-04 14:00', '');
INSERT INTO Draw VALUES (84, 5, 'Draw #4', '2020-07-05 12:30', '');
INSERT INTO Draw VALUES (86, 5, 'Draw #6', '2020-07-05 19:00', '');
INSERT INTO Draw VALUES (87, 5, 'Draw #7', '2020-07-05 21:40', '');
INSERT INTO Draw VALUES (89, 5, 'Draw #9', '2020-07-06 11:30', '');
INSERT INTO Draw VALUES (810, 5, 'Draw #10', '2020-07-06 14:15', '');
INSERT INTO Draw VALUES (811, 5, 'Draw #11', '2020-07-06 16:45', '');
INSERT INTO Draw VALUES (812, 5, 'Draw #12', '2020-07-07 08:15', '');
INSERT INTO Draw VALUES (813, 5, 'Draw #13', '2020-07-07 11:00', '');

INSERT INTO Game VALUES (844, 'pools', 'Game 44', NULL, NULL, 813, 19, 15, 'red', 'yellow', NULL, NULL, 'B', TRUE, 15);
INSERT INTO Game VALUES (842, 'pools', 'Game 42', NULL, NULL, 813, 25, 16, 'red', 'yellow', NULL, NULL, 'C', TRUE, 16);
INSERT INTO Game VALUES (843, 'pools', 'Game 43', NULL, NULL, 813, 20, 24, 'red', 'yellow', NULL, NULL, 'D', TRUE, 20);
INSERT INTO Game VALUES (841, 'pools', 'Game 41', NULL, NULL, 813, 33, 22, 'red', 'yellow', NULL, NULL, 'E', TRUE, 22);
INSERT INTO Game VALUES (834, 'pools', 'Game 34', NULL, NULL, 811, 15, 23, 'red', 'yellow', 844, NULL, 'D', TRUE, 15);
INSERT INTO Game VALUES (833, 'pools', 'Game 33', NULL, NULL, 811, 24, 34, 'red', 'yellow', 843, NULL, 'E', TRUE, 24);
INSERT INTO Game VALUES (837, 'pools', 'Game 37', NULL, NULL, 812, 35, 22, 'red', 'yellow', 841, NULL, 'A', TRUE, 22);
INSERT INTO Game VALUES (838, 'pools', 'Game 38', NULL, NULL, 812, 16, 28, 'red', 'yellow', 842, NULL, 'D', TRUE, 16);
INSERT INTO Game VALUES (829, 'pools', 'Game 29', NULL, NULL, 810, 22, 37, 'red', 'yellow', 837, NULL, 'E', TRUE, 22);
INSERT INTO Game VALUES (839, 'pools', 'Game 39', NULL, NULL, 811, 36, 33, 'red', 'yellow', 841, NULL, 'A', TRUE, 33);
INSERT INTO Game VALUES (835, 'pools', 'Game 35', NULL, NULL, 811, 32, 20, 'red', 'yellow', 843, NULL, 'B', TRUE, 20);
INSERT INTO Game VALUES (836, 'pools', 'Game 36', NULL, NULL, 811, 19, 21, 'red', 'yellow', 844, NULL, 'C', TRUE, 19);
INSERT INTO Game VALUES (832, 'pools', 'Game 32', NULL, NULL, 810, 28, 31, 'red', 'yellow', 838, NULL, 'A', TRUE, 14);
INSERT INTO Game VALUES (831, 'pools', 'Game 31', NULL, NULL, 810, 38, 35, 'red', 'yellow', 837, NULL, 'B', TRUE, 35);
INSERT INTO Game VALUES (830, 'pools', 'Game 30', NULL, NULL, 810, 16, 30, 'red', 'yellow', 838, NULL, 'C', TRUE, 16);
INSERT INTO Game VALUES (840, 'pools', 'Game 40', NULL, NULL, 810, 29, 25, 'red', 'yellow', 842, NULL, 'D', TRUE, 25);
INSERT INTO Game VALUES (827, 'pools', 'Game 27', NULL, NULL, 89,  27, 34, 'red', 'yellow', 833, NULL, 'B', TRUE, 34);
INSERT INTO Game VALUES (826, 'pools', 'Game 26', NULL, NULL, 89,  15, 18, 'red', 'yellow', 834, NULL, 'C', TRUE, 15);
INSERT INTO Game VALUES (825, 'pools', 'Game 25', NULL, NULL, 89,  26, 24, 'red', 'yellow', 833, NULL, 'D', TRUE, 24);
INSERT INTO Game VALUES (828, 'pools', 'Game 28', NULL, NULL, 89,  23, 17, 'red', 'yellow', 834, NULL, 'A', TRUE, 23);
INSERT INTO Game VALUES (823, 'pools', 'Game 23', NULL, NULL, 89,  33, 20, 'red', 'yellow', 835, 839, 'E', TRUE, 20);
INSERT INTO Game VALUES (821, 'pools', 'Game 21', NULL, NULL, 87,  36, 32, 'red', 'yellow', 835, 839, 'C', TRUE, 32);
INSERT INTO Game VALUES (820, 'pools', 'Game 20', NULL, NULL, 87,  17, 31, 'red', 'yellow', 828, 832, 'D', TRUE, 31);
INSERT INTO Game VALUES (819, 'pools', 'Game 19', NULL, NULL, 87,  35, 34, 'red', 'yellow', 827, 831, 'E', TRUE, 34);
INSERT INTO Game VALUES (818, 'pools', 'Game 18', NULL, NULL, 86,  28, 23, 'red', 'yellow', 828, 832, 'D', TRUE, 23);
INSERT INTO Game VALUES (816, 'pools', 'Game 16', NULL, NULL, 86,  28, 30, 'red', 'yellow', 826, 830, 'E', TRUE, 18);
INSERT INTO Game VALUES (824, 'pools', 'Game 24', NULL, NULL, 87,  19, 29, 'red', 'yellow', 836, 840, 'A', TRUE, 19);
INSERT INTO Game VALUES (822, 'pools', 'Game 22', NULL, NULL, 87,  21, 25, 'red', 'yellow', 836, 840, 'B', TRUE, 21);
INSERT INTO Game VALUES (810, 'pools', 'Game 10', NULL, NULL, 84,  36, 21, 'red', 'yellow', 822, 821, 'E', TRUE, 21);
INSERT INTO Game VALUES (815, 'pools', 'Game 15', NULL, NULL, 86,  22, 36, 'red', 'yellow', 825, 829, 'A', TRUE, 36);
INSERT INTO Game VALUES (813, 'pools', 'Game 13', NULL, NULL, 86,  24, 37, 'red', 'yellow', 825, 829, 'B', TRUE, 24);
INSERT INTO Game VALUES (817, 'pools', 'Game 17', NULL, NULL, 86,  38, 27, 'red', 'yellow', 827, 831, 'C', TRUE, 27);
INSERT INTO Game VALUES (809, 'pools', 'Game 9',  NULL, NULL, 84,  32, 25, 'red', 'yellow', 822, 821, 'A', TRUE, 25);
INSERT INTO Game VALUES (814, 'pools', 'Game 14', NULL, NULL, 84,  16, 15, 'red', 'yellow', 826, 830, 'B', TRUE, 15);
INSERT INTO Game VALUES (811, 'pools', 'Game 11', NULL, NULL, 84,  20, 29, 'red', 'yellow', 824, 823, 'C', TRUE, 29);
INSERT INTO Game VALUES (812, 'pools', 'Game 12', NULL, NULL, 84,  33, 19, 'red', 'yellow', 824, 823, 'D', TRUE, 19);
INSERT INTO Game VALUES (807, 'pools', 'Game 7',  NULL, NULL, 82,  34, 31, 'red', 'yellow', 820, 819, 'B', TRUE, 31);
INSERT INTO Game VALUES (808, 'pools', 'Game 8',  NULL, NULL, 82,  17, 35, 'red', 'yellow', 820, 819, 'C', TRUE, 17);
INSERT INTO Game VALUES (806, 'pools', 'Game 6',  NULL, NULL, 82,  23, 27, 'red', 'yellow', 818, 817, 'D', TRUE, 23);
INSERT INTO Game VALUES (805, 'pools', 'Game 5',  NULL, NULL, 82,  38, 28, 'red', 'yellow', 818, 817, 'E', TRUE, 28);
INSERT INTO Game VALUES (801, 'pools', 'Game 1',  NULL, NULL, 81,  24, 16, 'red', 'yellow', 814, 813, 'A', TRUE, 16);
INSERT INTO Game VALUES (803, 'pools', 'Game 3',  NULL, NULL, 81,  26, 30, 'red', 'yellow', 816, 815, 'B', TRUE, 30);
INSERT INTO Game VALUES (804, 'pools', 'Game 4',  NULL, NULL, 81,  18, 22, 'red', 'yellow', 816, 815, 'C', TRUE, 18);
INSERT INTO Game VALUES (802, 'pools', 'Game 2',  NULL, NULL, 81,  37, 15, 'red', 'yellow', 814, 813, 'D', TRUE, 15);
