name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bonspiel-server" #Must be unique in Heroku
          heroku_email: "tejas2@pdx.edu"
          buildpack: "" #OPTIONAL
          branch: "" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          usedocker: true #OPTIONAL and DEFAULT - false
          docker_heroku_process_type: "" #OPTIONAL and DEFAULT - "web"
